name: build

on:
  schedule:
    - cron: "0 12 * * *"
  push:
    paths-ignore:
      - "*.md"
      - "*.txt"
      - "*.png"
  pull_request:

env:
  IMAGE_NAME: adamdecaf/atmoz-sftp

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # for proper signature verification
          submodules: true # for shunit2

      - name: Run ShellCheck
        if: runner.os == 'Linux'
        uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: tests/shunit2

      - name: Build debian image
        if: runner.os == 'Linux'
        run: |
          docker build . \
            --pull=true \
            --file=Dockerfile \
            --tag="$IMAGE_NAME:latest" \
            --tag="$IMAGE_NAME:debian" \
            --label="org.opencontainers.image.source=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" \
            --label="org.opencontainers.image.revision=$GITHUB_SHA" \
            --label="org.opencontainers.image.created=$(date --rfc-3339=seconds)"

      - name: Test debian image
        if: runner.os == 'Linux'
        run: tests/run $IMAGE_NAME:debian

      - name: Build alpine image
        if: runner.os == 'Linux'
        run: |
          docker build . \
            --pull=true \
            --file=Dockerfile-alpine \
            --tag="$IMAGE_NAME:alpine" \
            --label="org.opencontainers.image.source=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" \
            --label="org.opencontainers.image.revision=$GITHUB_SHA" \
            --label="org.opencontainers.image.created=$(date --rfc-3339=seconds)"

      - name: Test alpine image
        if: runner.os == 'Linux'
        run: tests/run $IMAGE_NAME:alpine

      - name: Build Windows image
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          docker build . \
            --pull=true \
            --file=Dockerfile-windows \
            --tag="$IMAGE_NAME:windows" \
            --label="org.opencontainers.image.source=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" \
            --label="org.opencontainers.image.revision=$GITHUB_SHA" \
            --label="org.opencontainers.image.created=$(date --rfc-3339=seconds)"

      - name: Verify signature
        if: github.ref == 'refs/heads/master'
        uses: atmoz/git-verify-ref@master
        with:
          import-github-users: atmoz

      - name: Push images to Docker Hub registry
        if: github.ref == 'refs/heads/master'
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login \
             -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

          docker push --all-tags $IMAGE_NAME
          docker logout

      - name: Push images to GitHub registry
        if: github.ref == 'refs/heads/master'
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com \
             -u ${{ github.actor }} --password-stdin

          TAG_DEBIAN=docker.pkg.github.com/$GITHUB_REPOSITORY/debian
          TAG_ALPINE=docker.pkg.github.com/$GITHUB_REPOSITORY/alpine
          TAG_WINDOWS=docker.pkg.github.com/$GITHUB_REPOSITORY/windows
          docker tag $IMAGE_NAME:debian $TAG_DEBIAN
          docker tag $IMAGE_NAME:alpine $TAG_ALPINE
          docker tag $IMAGE_NAME:windows $TAG_WINDOWS
          docker push $TAG_DEBIAN
          docker push $TAG_ALPINE
          docker push $TAG_WINDOWS
          docker logout docker.pkg.github.com
